# Generated by Django 2.1.2 on 2020-04-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cibil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_History',
            fields=[
                ('Credit_Card_No', models.CharField(max_length=19, primary_key=True, serialize=False)),
                ('Credit_Limit', models.IntegerField()),
                ('Balance', models.FloatField()),
                ('Payment_Date', models.DateField()),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cibil.Personal_Information')),
            ],
        ),
    ]
