# Generated by Django 2.1.2 on 2020-07-23 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cibil', '0003_application_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emi_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emi_Duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Interest_Rate', models.FloatField()),
                ('Payment_Status', models.CharField(max_length=20)),
                ('Amount_To_Pay', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='loan_details',
            name='Loan_Interest_Rate',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='loan_details',
            name='On_Emi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emi_details',
            name='Loan_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cibil.Loan_Details'),
        ),
    ]
