# Generated by Django 2.1.2 on 2020-07-23 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cibil', '0005_auto_20200723_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emi_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emi_Duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Interest_Rate', models.FloatField()),
                ('Payment_Status', models.CharField(max_length=20)),
                ('Amount_To_Pay', models.FloatField()),
                ('Loan_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cibil.Loan_Details')),
            ],
        ),
    ]
