# Generated by Django 2.1.2 on 2020-07-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi_details',
            name='Curr_Closing_Amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='emi_details',
            name='Curr_Emi_Amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='emi_details',
            name='Curr_Interest_Amount',
            field=models.FloatField(default=0),
        ),
    ]
