# Generated by Django 2.1.2 on 2020-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emi', '0002_auto_20200724_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi_details',
            name='Curr_Closing_Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emi_details',
            name='Curr_Emi_Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emi_details',
            name='Curr_Interest_Amount',
            field=models.FloatField(),
        ),
    ]
