# Generated by Django 3.0.5 on 2020-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Credit_Card_No', models.CharField(max_length=40)),
                ('Loan_Id', models.CharField(max_length=40)),
                ('amount', models.IntegerField(default=0)),
                ('razorpayid', models.CharField(default='', max_length=255)),
                ('razorpaypaymentid', models.CharField(default='', max_length=255)),
                ('razorpaysignature', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
